### PR TITLE
Don't display case study icon for the page we're currently on

### LINKED ISSUE #440: Incorrect tiles shown on case-study pages
**Description of the issue:**
On the case-study pages there is a tile container with links to other case-studies. Sometimes it shows links to the page you are currently viewing. eg. When you view the F&M case-study page in mobile view, the only tile shown is one with links to the F&M page you are already on.

We need to make sure none of the links shown are for the case-study page you are currently on.

We need to create an extra (4th) case-study tile to fill any gaps if one of the other tiles need to be removed.

### PR DESCRIPTION
**Pull request by Xanndarr**
Fixes #440 

Blocked:
- [ ] Content for case study icons
- [ ] Images for case study icons

### CODE REVIEW

**Comment by chris-brookes** [comment]
This is blocked until we get the image and content for the retailer (Tesco) tile.

File: site/pages/our-work/case-study/what-to-read-next/slice.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+import InlineSVG from 'svg-inline-react';
+
+import styles from './style.css';
+import arrowSVG from '../../../../../assets/images/SVG/arrow.svg';
+
+type WhatToReadNextSliceProps = {
+  details: Object,
+};
+
+const WhatToReadNextSlice = ({ details }: WhatToReadNextSliceProps) => {
```
Comment (martinhartt) [inline site/pages/our-work/case-study/what-to-read-next/slice.js]: Here we could extract all the properties out of details so that they are their own properties in the props.

Kinda like this:

```javascript
const WhatToReadNextSlice = ({ name, link, tagline, image }: WhatToReadNextSliceProps) => {
```
This way we can add type-checking for them with flow. And when we use the component we can use the spread operator: `<WhatToReadNextSlice ...details />`

Comment (martinhartt) [inline site/pages/our-work/case-study/what-to-read-next/slice.js]: UPDATE: This is sadly not possible as the spread operator is not supported in this version of node.

File: site/pages/our-work/case-study/what-to-read-next/index.js [hunk 2]
```diff
@@ -1,64 +1,57 @@
...
+    name: 'Financial Times',
+    tagline: 'Lasting change for a media giant',
+    image: financialTimesImage,
+    link: '/our-work/case-study/financial-times/',
+  },
+  camdenMarket: {
+    name: 'Camden Market',
+    tagline: 'Taking steps towards a digital future',
+    image: camdenMarketImage,
+    link: 'our-work/case-study/camden-market/',
```
Comment (chris-brookes) [inline site/pages/our-work/case-study/what-to-read-next/index.js]: @martinhartt - Camden Market and Retailer are missing a / from the start of their link.

**Comment by chris-brookes** [comment]
The tile for your current case study page is being shown. 

It may not be shown straight away, but just refresh the page a few times and it should appear.

**Comment by martinhartt** [comment]
Good spot @chris-brookes, I fixed it now 👍

**Comment by gregdorward** [comment]
Is this one good to go @chris-brookes?

**Comment by chris-brookes** [comment]
yeah I believe so...
No it's got a dev sign-off I'll merge it.
